---
title: "Using the main Function"
output:
    rmarkdown::html_vignette
vignette: >
    %\VignetteIndexEntry{"Example of using the main() function"}
    %\VignetteEncoding{UTF-8}
    %\VignetteEngine{knitr::rmarkdown}
editor_options: 
    markdown: 
    wrap: 72
---

# Introduction

Welcome to the **EpigeneticAgePipeline** package, an R toolkit designed for the comprehensive processing and analysis of DNA methylation data. Our package aims to provide an efficient and integrated solution for several key functionalities: The purpose of this vigentte is to show usage of the **main()** function.

## Key Features

### Epigenetic Age Measures

-   **Generate diverse epigenetic age measures** directly from beta values or IDAT files.
-   Includes renowned measures such as the **Horvath Clock**, **Hannum Clock**, **Levine/PhenoAge Clock**, among others.
-   Each clock offers unique sets of CpG sites, array types, and cell type specificities for different tissue types.

### Visualization and Quantitative Analysis

-   Presents visual and quantitative mediums to **explore and analyze various epigenetic age measures**.
-   Offers matrix plots, line plots, and grouped bar charts for **easy interpretation and comparison** of age estimates against chronological age and covariates.

### Cell Count Estimation

-   Utilizes methylation data from provided IDAT files to **estimate cell counts** for specific cell types including B Cells, CD4T Cells, CD8T Cells, Granulocytes, Monocytes, and Nucleated Red Blood cells.

# Installation

To install the EpigeneticAgePipeline, which will include the data used in the upcoming example:

``` r
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
packages_to_install <- c(
    "minfi",
    "IlluminaHumanMethylationEPICanno.ilm10b4.hg19",
    "IlluminaHumanMethylationEPICmanifest",
    "methylclock",
    "methylclockData",
    "FlowSorted.CordBlood.450k",
    "IlluminaHumanMethylation450kmanifest",
    "IlluminaHumanMethylation450kanno.ilmn12.hg19",
    "IlluminaHumanMethylation27kmanifest",
    "IlluminaHumanMethylation27kanno.ilmn12.hg19",
    "AnnotationHub",
    "AnnotationHubData",
    "base64",
    "beanplot",
    "ggplot2",
    "dplyr",
    "tidyr",
    "annotate",
    "magick",
    "pdftools"
)
for (package in packages_to_install) {
    if (!requireNamespace(package, quietly = TRUE)) {
        BiocManager::install(package)
    }
}
if (!requireNamespace("S4Vectors", quietly = TRUE)) {
    BiocManager::install("S4Vectors", force = TRUE)
}
remotes::install_github('CastellaniLab/EpigeneticAgePipeline')
library(EpigeneticAgePipeline)
downloadDirectory <- "EpigeneticAgePipelineDataset-main"
downloadURL <- paste0("https://github.com/StanRaye/",
                        "EpigeneticAgePipelineDataset",
                        "/archive/refs/heads/main.zip")
installDirectory <- paste0(path.package("EpigeneticAgePipeline"),"/extdata/")
setwd(installDirectory)
utils::download.file(url = downloadURL, destfile = "asdf.zip")
utils::unzip("asdf.zip", exdir = installDirectory)
extractedFiles <- list.files(paste0(installDirectory, downloadDirectory),
                                    full.names = TRUE)
file.copy(from = extractedFiles, to = installDirectory, overwrite = TRUE,
            recursive = TRUE)
```

# Example of Running the Main Function Without Covariates

## 1. Setup

Load the package and identify the directory where methylation data is stored.

```{R}
library("EpigeneticAgePipeline")
myDirectory <- paste0(path.package("EpigeneticAgePipeline"),"/extdata/")
```

## 2. Data Source

```{R}
message("The data used in this example was obtained from:\n")
message("https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE197646\n\n")
```

## 3. Run Analysis

```{R}
if (file.exists(paste0(myDirectory, "betaValues.csv"))) {
    main(
        directory = myDirectory,
        useBeta = TRUE,
        arrayType = "450K",
        useSampleSheet = FALSE
    )  
    knitr::kable(read.table("epigeneticAge.txt"))
}
```

```{R echo=FALSE}
sessionInfo()
```

# Example of Running the Main Function With Covariates

## 1. Setup

Load the package and identify the directory where methylation and covariate data is stored.

```{R}
library("EpigeneticAgePipeline")
myDirectory <- paste0(path.package("EpigeneticAgePipeline"),"/extdata/")
```

## 2. Data Source

```{R}
message("The data used in this example was obtained from:\n")
message("https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE197646\n\n")
```

## 3. Example .csv File Containing Covariate Data

```{R}
knitr::kable(read.csv(paste0(myDirectory, "Sample_Sheet.csv")))
```

## 4. Run Analysis

```{R}
if (file.exists(paste0(myDirectory, "betaValues.csv"))) {
    main(
        directory = myDirectory,
        useBeta = TRUE,
        arrayType = "450K",
        useSampleSheet = TRUE
    )  
    print(knitr::kable(read.table("epigeneticAge.txt")))
    print(magick::image_read_pdf(paste0(myDirectory, 
                                                "matrixplotHorvath.pdf")))
}
```

```{R echo=FALSE}
sessionInfo()
```
